'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

type Bankai={name:string;user:string;section:string;command:string;purpose:string;ability:string;accent:number;hex:string;mode:string;projects:string[]};
const BANKAIS:Bankai[]=[
['TENSA ZANGETSU','ICHIGO KUROSAKI','SPEED & POWER','BANKAI: TENSA ZANGETSU','Fast systems. Focused execution. High-performance engineering.','Compressed reiatsu becomes velocity, durability and destructive output.',0xff6b00,'#ff6b00','tensa',['Real-time systems','WebGL performance engine','Lightning-fast API work']],
['TRUE BANKAI','ICHIGO KUROSAKI','HYBRID INTELLIGENCE','TRUE BANKAI // HYBRID SOUL','Full-stack systems connecting AI, backend infrastructure and interfaces.','Black and white power merge into one adaptive architecture.',0xc8b8ff,'#c8b8ff','hybrid',['AI + backend integration','RAG applications','Distributed LLM experiments']],
['ZANKA NO TACHI','GENRYŪSAI YAMAMOTO','LEGACY & FIRE','BANKAI: ZANKA NO TACHI','Systems, research and lessons designed to survive the moment.','Four directional powers become one concentrated destructive edge.',0xff4b21,'#ff4b21','fire',['Research systems','Infrastructure / security work','Long-lived engineering lessons']],
['KATEN KYŌKOTSU: KARAMATSU SHINJŪ','SHUNSUI KYŌRAKU','STORIES & CASE STUDIES','BANKAI: KATEN KYŌKOTSU: KARAMATSU SHINJŪ','Every project has a constraint, conflict, decision and outcome.','A four-act narrative turns technical problems into readable stories.',0x9b7dff,'#9b7dff','story',['Technical case studies','Failure → lesson → redesign','Team and client stories']],
['SENBONZAKURA KAGEYOSHI','BYAKUYA KUCHIKI','PRECISION & ELEGANCE','BANKAI: SENBONZAKURA KAGEYOSHI','Clean architecture, deliberate abstractions and measurable quality.','Countless fragments become one precise system.',0xff8fd5,'#ff8fd5','petals',['Clean architecture','Test-focused development','Scalable project design']],
['DAIGUREN HYŌRINMARU','TŌSHIRŌ HITSUGAYA','TIME & OPTIMIZATION','BANKAI: DAIGUREN HYŌRINMARU','Deadlines become visible systems: scope, time, risk and delivery.','Ice petals track the remaining window until mastery arrives.',0x72d9ff,'#72d9ff','ice',['Sprint planning','Performance optimization','Learning roadmaps']],
['KONJIKI ASHISOGI JIZŌ','MAYURI KUROTSUCHI','EXPERIMENTAL TECH','BANKAI: KONJIKI ASHISOGI JIZŌ','Research, prototypes and strange ideas that become useful tools.','A customizable counter is generated for the problem in front of it.',0xd7ff3f,'#d7ff3f','poison',['Novel graph tooling','Custom algorithms','Experimental AI frameworks']],
['MINAZUKI','RETSU UNOHANA','REPAIR & RESILIENCE','BANKAI: MINAZUKI','Infrastructure that can recover, monitor itself and keep serving.','Damage and healing coexist in a continuous reliability loop.',0x76ffb1,'#76ffb1','acid',['Disaster recovery','Automated backups','Health monitoring / self-healing']],
['KOKUJŌ TENGEN MYŌŌ','SAJIN KOMAMURA','LARGE-SCALE SYSTEMS','BANKAI: KOKUJŌ TENGEN MYŌŌ','Distributed architecture and enterprise reliability beyond one machine.','A colossal guardian mirrors the scale of the system.',0xff3030,'#ff3030','giant',['Distributed recovery','Global load balancing','Cross-datacenter replication']],
['KAMISHINI NO YARI','GIN ICHIMARU','LONG-RANGE IMPACT','BANKAI: KAMISHINI NO YARI','A small interface can move a huge distributed system.','A blade stretches across distance at extreme speed.',0xe8f8ff,'#e8f8ff','spear',['gRPC services','Message queues','Distributed databases']],
['SUZUMUSHI TSUISHIKI: ENMA KŌRO','KANAME TŌSEN','SENSORY ANALYTICS','BANKAI: SUZUMUSHI TSUISHIKI: ENMA KŌRO','Remove noise until the signal is impossible to miss.','A black field suppresses everything except the insight.',0x6578ff,'#6578ff','void',['Pattern recognition','Data mining','Model explainability']],
['KINSHARA BUTŌDAN','RŌJŪRŌ “ROSE” ŌTORIBASHI','CREATIVE DIRECTION','BANKAI: KINSHARA BUTŌDAN','Design systems, interaction, motion and interfaces that communicate.','Music becomes illusion; design becomes an experience.',0xffcf6b,'#ffcf6b','gold',['Design systems','Motion libraries','Interactive visual work']],
['TEKKEN TACHIKAZE','KENSEI MUGURUMA','RAW PERFORMANCE','BANKAI: TEKKEN TACHIKAZE','Benchmarking, profiling and ruthless removal of bottlenecks.','Continuous contact means continuous concussive force.',0xff5a3d,'#ff5a3d','force',['Algorithm optimization','Benchmark suites','Runtime tuning']],
['SŌŌ ZABIMARU','RENJI ABARAI','GROWTH TRAJECTORY','BANKAI: SŌŌ ZABIMARU','Skills accumulate through projects, experiments and mentorship.','A skeletal serpent grows with every completed milestone.',0xb979ff,'#b979ff','snake',['Career progression','Mentorship','Learning outcomes']],
['RYŪMON HŌZŌKUMARU','IKKAKU MADARAME','COMPOUNDING EFFORT','BANKAI: RYŪMON HŌZŌKUMARU','Long projects reward patience and accumulated effort.','A crest fills until one decisive strike is possible.',0xe74343,'#e74343','dragon',['Long-term initiatives','Compounding learning','Year-scale goals']],
['KŌŌ MONSHŌ','CHŌJIRŌ SASAKIBE','LEADERSHIP','BANKAI: KŌŌ MONSHŌ','Architecture is coordination: people, responsibilities and decisions.','Lightning creates a visible hierarchy of roles and dependencies.',0xffe45c,'#ffe45c','lightning',['Team projects','Delegation','Strategic planning']],
['HAKKA NO TOGAME','RUKIA KUCHIKI','SACRIFICE & PERFECTION','BANKAI: HAKKA NO TOGAME','Some breakthroughs require removing what no longer belongs.','Absolute cold freezes the environment and forces a deliberate reset.',0xdffaff,'#dffaff','white',['Difficult technical decisions','Course corrections','Focused simplification']],
['KANNONBIRAKI BENIHIME ARATAME','KISUKE URAHARA','RESTRUCTURE & FIX','BANKAI: KANNONBIRAKI BENIHIME ARATAME','Debugging means opening the system and rebuilding the right part.','Anything in range can be split, restructured and stitched together.',0xff7652,'#ff7652','repair',['Debugging','Architectural refactoring','System redesign']],
['SAKAHADĒ','SHINJI HIRAKO','PERSPECTIVE SHIFT','INVERSION // CAN’T FEAR YOUR OWN WORLD','Invert assumptions. Reframe the problem.','Perspective itself becomes the weapon.',0xffc45c,'#ffc45c','invert',['Unconventional approaches','Blue-sky thinking','Paradigm shifts']],
['SHINKA HAKKŌ KEN','NANAO ISE / SHUNSUI KYŌRAKU','SECURITY & PROTECTION','DIVINE EIGHT MIRROR SWORD','Good systems defend users, data and invariants.','A mirror absorbs hostile force and reflects it back.',0xbdeeff,'#bdeeff','mirror',['Cybersecurity','Encryption','Defensive architecture']],
['UNNAMED BANKAI','KENPACHI ZARAKI','RAW IMPACT','BANKAI // UNTAMED','Ambitious work that changes the game.','Pure destructive output with no concern for elegance.',0xff1738,'#ff1738','berserk',['Breakthrough builds','Highest-impact work','Game-changing experiments']],
['RESURRECCIÓN // FINAL PORTAL','MUSAB WAQAR','CONTACT & NEXT ARC','FINAL FORM: OPEN THE GATE','A portfolio is a doorway. The next system can be built together.','The Bankai archive collapses into a single portal.',0xffd166,'#ffd166','final',['Research collaboration','FYP / engineering collaboration','International MS / research opportunities']]
].map(x=>({name:x[0] as string,user:x[1] as string,section:x[2] as string,command:x[3] as string,purpose:x[4] as string,ability:x[5] as string,accent:x[6] as number,hex:x[7] as string,mode:x[8] as string,projects:x[9] as string[]}));
const profile={name:'Musab Waqar',role:'Co-Founder & CTO @ NanoCoders',university:'BS Computer Science · FAST NUCES Peshawar',graduation:'June 2027',motto:'Foundation → Mechanism → Implementation → Optimization → Real-world usage'};
const tech=['C','C++','Python','TypeScript','React','Next.js','Docker','Apache Kafka','Spark','PySpark','Hadoop','NLP','RAG','Neo4j','Apache AGE','PostgreSQL','Databricks','Linux'];

export default function AnimeBankaiPortfolio(){
 const mount=useRef<HTMLDivElement>(null);const target=useRef(0);const activeRef=useRef(0);const [active,setActive]=useState(0);const [menu,setMenu]=useState(false);const [selected,setSelected]=useState<Bankai|null>(null);const current=BANKAIS[active];const ids=useMemo(()=>BANKAIS.map((_,i)=>String(i+1).padStart(2,'0')),[]);
 useEffect(()=>{
  if(!mount.current)return;const root=mount.current;const scene=new THREE.Scene();const cam=new THREE.PerspectiveCamera(42,1,.1,160);cam.position.set(0,.25,10);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
  const resize=()=>{const w=root.clientWidth||innerWidth,h=root.clientHeight||innerHeight;cam.aspect=w/h;cam.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();window.addEventListener('resize',resize);
  scene.add(new THREE.HemisphereLight(0xbdd7ff,0x050507,1.25));const key=new THREE.DirectionalLight(0xffffff,2.1);key.position.set(4,8,7);scene.add(key);const stage=new THREE.Group();scene.add(stage);
  const mat=(c:number,o=1)=>new THREE.MeshStandardMaterial({color:c,roughness:.32,metalness:.48,transparent:o<1,opacity:o,emissive:c,emissiveIntensity:.08});const glow=(c:number,o=.6)=>new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide});
  const outline=(m:THREE.Mesh)=>m.add(new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry,25),new THREE.LineBasicMaterial({color:0x030303,transparent:true,opacity:.82})));
  const sword=(g:THREE.Group,c:number,scale=1)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(.18,4.8,.08),mat(c));b.scale.setScalar(scale);b.rotation.z=-.08;outline(b);g.add(b);const q=new THREE.Mesh(new THREE.TorusGeometry(.34,.07,10,64),mat(0x14171a));q.position.y=-2.05*scale;g.add(q)};
  const particles=(g:THREE.Group,c:number,n:number)=>{const geo=new THREE.BufferGeometry(),p=new Float32Array(n*3);for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,r=Math.pow(Math.random(),.45)*(2.5+Math.random()*4);p[i*3]=Math.cos(a)*r;p[i*3+1]=(Math.random()-.5)*7;p[i*3+2]=Math.sin(a)*r-2}geo.setAttribute('position',new THREE.BufferAttribute(p,3));g.add(new THREE.Points(geo,new THREE.PointsMaterial({color:c,size:.03,transparent:true,opacity:.7,depthWrite:false,blending:THREE.AdditiveBlending})))};
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(70,70,80,80),new THREE.MeshStandardMaterial({color:0x020408,roughness:.85,metalness:.1,wireframe:true,transparent:true,opacity:.24}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.2;stage.add(floor);
  for(let i=0;i<52;i++){const h=.5+Math.random()*5.5;const p=new THREE.Mesh(new THREE.BoxGeometry(.18+Math.random()*.6,h,.18+Math.random()*.6),new THREE.MeshStandardMaterial({color:0x0a1119,wireframe:true,transparent:true,opacity:.42}));p.position.set((Math.random()-.5)*30,-3.1+h/2,-7-Math.random()*42);stage.add(p)}
  const stars=new THREE.BufferGeometry(),sp=new Float32Array(900*3);for(let i=0;i<900;i++){sp[i*3]=(Math.random()-.5)*42;sp[i*3+1]=(Math.random()-.5)*23;sp[i*3+2]=-Math.random()*65}stars.setAttribute('position',new THREE.BufferAttribute(sp,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xdbe7ff,size:.018,transparent:true,opacity:.55})));
  const hero=new THREE.Group();hero.position.set(0,-.3,.1);hero.rotation.z=-.12;hero.scale.setScalar(2.15);stage.add(hero);
  // CC0 asset: BoQsc/cc0-melee-weapons-pack-glb/Katana/Katana.glb
  new GLTFLoader().load('https://raw.githubusercontent.com/BoQsc/cc0-melee-weapons-pack-glb/main/Katana/Katana.glb',g=>{g.scene.traverse(o=>{const m=o as THREE.Mesh;if(m.isMesh)m.frustumCulled=true});hero.add(g.scene)},()=>{},()=>sword(hero,0xe9edf2));
  const groups=BANKAIS.map((s,i)=>{const g=new THREE.Group();g.visible=i===0;g.position.set(3.5,0,-1);const halo=new THREE.Mesh(new THREE.TorusGeometry(2.2,.035,12,128),glow(s.accent,.8));halo.rotation.x=Math.PI/2;g.add(halo);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,3),mat(s.accent,.88));core.scale.set(.8,1.25,.8);outline(core);g.add(core);particles(g,s.accent,i===4?900:260);if(i!==0)sword(g,s.accent,.8);stage.add(g);return g});
  const onScroll=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);const exact=Math.min(1,Math.max(0,scrollY/max))*(BANKAIS.length-1);target.current=exact;const n=Math.min(BANKAIS.length-1,Math.round(exact));if(n!==activeRef.current){activeRef.current=n;setActive(n)}};window.addEventListener('scroll',onScroll,{passive:true});onScroll();
  let raf=0;const tick=()=>{raf=requestAnimationFrame(tick);const t=target.current,local=t-activeRef.current;stage.position.x+=(Math.sin(t*.8)*.12-stage.position.x)*.06;stage.position.y+=(-local*.18-stage.position.y)*.06;stage.rotation.y+=((t-activeRef.current)*.045-stage.rotation.y)*.06;cam.position.x+=(local*.9-cam.position.x)*.06;cam.position.z+=(10-Math.abs(local)*.3-cam.position.z)*.06;groups.forEach((g,i)=>{const d=i-t;g.visible=Math.abs(d)<1.7;g.position.x=3.5+d*1.45;g.position.y=Math.sin(d)*.3;g.rotation.y=d*.15;g.scale.setScalar(Math.max(.55,1-Math.abs(d)*.22))});hero.rotation.y+=(local*.7-hero.rotation.y)*.07;hero.position.x+=(-local*.7-hero.position.x)*.07;renderer.render(scene,cam)};tick();
  return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('scroll',onScroll);renderer.dispose();root.removeChild(renderer.domElement);scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(Array.isArray(m.material))m.material.forEach(x=>x.dispose());else if(m.material)m.material.dispose()})};
 },[]);
 useEffect(()=>{const html=document.documentElement;html.style.scrollBehavior='smooth';return()=>{html.style.scrollBehavior='auto'}},[]);
 const jump=(i:number)=>{setMenu(false);const max=Math.max(0,document.documentElement.scrollHeight-innerHeight);window.scrollTo({top:max*(i/(BANKAIS.length-1)),behavior:'smooth'})};
 return <main className="portfolio" style={{'--scene-accent':current.hex} as React.CSSProperties}><div className="webgl-stage" ref={mount}/><div className="anime-speedlines"/><div className="anime-ink"/><div className="vignette"/><div className="scanlines"/>
  <header className="topbar"><a className="brand" href="#top">MUSAB<span>.</span>WAQAR</a><div className="system-label">BANKAI ARCHIVE <b>22 FORMS</b> · SCROLL-DRIVEN 3D</div><button className="menu-button" onClick={()=>setMenu(true)}>ARCHIVE <span>☰</span></button></header>
  <aside className="rail"><span>01</span><div><i style={{height:`${((active+1)/BANKAIS.length)*100}%`}}/></div><span>22</span></aside><div className="chapter-count">{ids[active]} / 22</div><div className="progress-line"><i style={{width:`${(active/(BANKAIS.length-1))*100}%`}}/></div>
  <div id="top" className="scroll-space">{BANKAIS.map((s,i)=><section className="bankai-section" key={s.name}><div className="section-inner"><div className="scene-copy"><div className="eyebrow">BANKAI ARCHIVE // {ids[i]} · {s.section}</div><h1>{s.name}</h1><div className="user-line">{s.user}</div><p>{s.purpose}</p><div className="command"><b>RELEASE</b>{s.command}</div><div className="ability"><b>ABILITY / PORTFOLIO TRANSLATION</b>{s.ability}</div><div className="actions"><button className="primary" onClick={()=>setSelected(s)}>OPEN PROJECT CORE ↗</button><button className="ghost" onClick={()=>jump(Math.min(i+1,21))}>NEXT BANKAI ↓</button></div></div><div className="project-panel"><div className="panel-kicker">ACTIVE FORM</div><h2>{s.section}</h2>{s.projects.map((p,j)=><button className="project-row" key={p} onClick={()=>setSelected({...s,purpose:p,ability:`${p} is represented here as a Bankai technique: measurable engineering impact, deliberate execution and visible transformation.`})}><span>0{j+1}</span><strong>{p}</strong><em>VIEW</em></button>)}<div className="tech-strip">{tech.slice((i*2)%tech.length,(i*2)%tech.length+6).map(t=><span key={t}>{t}</span>)}</div></div><div className="scroll-cue">SCROLL TO AWAKEN <span>↓</span></div></div></section>)}<section className="about-section"><div><div className="eyebrow">FINAL PORTAL // MUSAB WAQAR</div><h2>{profile.name}</h2><p>{profile.role}<br/>{profile.university}<br/>Graduating {profile.graduation}</p><p className="motto">“{profile.motto}”</p><div className="final-links"><a href="https://github.com/Musab-Waqar" target="_blank" rel="noreferrer">GITHUB</a><a href="https://musab-waqar-portfolio.vercel.app/" target="_blank" rel="noreferrer">PORTFOLIO</a><a href="https://www.linkedin.com/in/musab-waqar" target="_blank" rel="noreferrer">LINKEDIN</a><a href="mailto:musab@fast.edu">EMAIL</a></div></div></section></div>
  {menu&&<div className="menu-overlay"><div className="menu-head"><span>BANKAI ARCHIVE / SELECT FORM</span><button onClick={()=>setMenu(false)}>CLOSE ×</button></div><div className="menu-grid">{BANKAIS.map((s,i)=><button key={s.name} className={i===active?'selected':''} onClick={()=>jump(i)}><small>{ids[i]}</small><b>{s.name}</b><span>{s.section}</span></button>)}</div></div>}
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="archive-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">PROJECT CORE / {ids[active]}</div><h2>{selected.name}</h2><p>{selected.purpose}</p><p>{selected.ability}</p><div className="modal-tags">{selected.projects.map(x=><span key={x}>{x}</span>)}</div><div className="modal-links"><a href="https://github.com/Musab-Waqar" target="_blank" rel="noreferrer">EXPLORE GITHUB ↗</a><a href="https://musab-waqar-portfolio.vercel.app/" target="_blank" rel="noreferrer">VIEW PORTFOLIO ↗</a></div></article></div>}
 </main>;
}
