'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { gsap } from 'gsap';

type Scene = { name: string; user: string; title: string; command: string; purpose: string; ability: string; accent: number; mode: string; projects: string[] };

const scenes: Scene[] = [
  { name:'TENSA ZANGETSU',user:'ICHIGO KUROSAKI',title:'SPEED & POWER',command:'BANKAI: TENSA ZANGETSU',purpose:'Fast systems. Focused execution. High-performance engineering.',ability:'Compressed reiatsu becomes velocity, durability and destructive output.',accent:0xff6b00,mode:'tensa',projects:['Real-time systems','WebGL performance engine','Lightning-fast API work'] },
  { name:'TRUE BANKAI',user:'ICHIGO KUROSAKI',title:'HYBRID INTELLIGENCE',command:'TRUE BANKAI // HYBRID SOUL',purpose:'Full-stack systems connecting AI, backend infrastructure and interfaces.',ability:'Black and white power merge into one adaptive architecture.',accent:0xc8b8ff,mode:'hybrid',projects:['AI + backend integration','RAG applications','Distributed LLM experiments'] },
  { name:'ZANKA NO TACHI',user:'GENRYŪSAI YAMAMOTO',title:'LEGACY & FIRE',command:'BANKAI: ZANKA NO TACHI',purpose:'Systems, research and lessons designed to survive the moment.',ability:'Four directional powers become one concentrated destructive edge.',accent:0xff4b21,mode:'fire',projects:['Research systems','Infrastructure/security work','Long-lived engineering lessons'] },
  { name:'KATEN KYŌKOTSU: KARAMATSU SHINJŪ',user:'SHUNSUI KYŌRAKU',title:'STORIES & CASE STUDIES',command:'BANKAI: KATEN KYŌKOTSU',purpose:'Every project has a constraint, conflict, decision and outcome.',ability:'A four-act narrative turns technical problems into readable stories.',accent:0x9b7dff,mode:'story',projects:['Technical case studies','Failure → lesson → redesign','Team and client stories'] },
  { name:'SENBONZAKURA KAGEYOSHI',user:'BYAKUYA KUCHIKI',title:'PRECISION & ELEGANCE',command:'BANKAI: SENBONZAKURA KAGEYOSHI',purpose:'Clean architecture, deliberate abstractions and measurable quality.',ability:'Countless fragments become one precise system.',accent:0xff8fd5,mode:'petals',projects:['Clean architecture','Test-focused development','Scalable project design'] },
  { name:'DAIGUREN HYŌRINMARU',user:'TŌSHIRŌ HITSUGAYA',title:'TIME & OPTIMIZATION',command:'BANKAI: DAIGUREN HYŌRINMARU',purpose:'Deadlines become visible systems: scope, time, risk and delivery.',ability:'Ice petals track the remaining window until mastery arrives.',accent:0x72d9ff,mode:'ice',projects:['Sprint planning','Performance optimization','Learning roadmaps'] },
  { name:'KONJIKI ASHISOGI JIZŌ',user:'MAYURI KUROTSUCHI',title:'EXPERIMENTAL TECH',command:'BANKAI: KONJIKI ASHISOGI JIZŌ',purpose:'Research, prototypes and strange ideas that become useful tools.',ability:'A customizable counter is generated for the problem in front of it.',accent:0xd7ff3f,mode:'poison',projects:['Novel graph tooling','Custom algorithms','Experimental AI frameworks'] },
  { name:'MINAZUKI',user:'RETSU UNOHANA',title:'REPAIR & RESILIENCE',command:'BANKAI: MINAZUKI',purpose:'Infrastructure that can recover, monitor itself and keep serving.',ability:'Damage and healing coexist in a continuous reliability loop.',accent:0x76ffb1,mode:'acid',projects:['Disaster recovery','Automated backups','Health monitoring / self-healing'] },
  { name:'KOKUJŌ TENGEN MYŌŌ',user:'SAJIN KOMAMURA',title:'LARGE-SCALE SYSTEMS',command:'BANKAI: KOKUJŌ TENGEN MYŌŌ',purpose:'Distributed architecture and enterprise reliability beyond one machine.',ability:'A colossal guardian mirrors the scale of the system.',accent:0xff3030,mode:'giant',projects:['Distributed recovery','Global load balancing','Cross-datacenter replication'] },
  { name:'KAMISHINI NO YARI',user:'GIN ICHIMARU',title:'LONG-RANGE IMPACT',command:'BANKAI: KAMISHINI NO YARI',purpose:'A small interface can move a huge distributed system.',ability:'A blade stretches across distance at extreme speed.',accent:0xe8f8ff,mode:'spear',projects:['gRPC services','Message queues','Distributed databases'] },
  { name:'SUZUMUSHI TSUISHIKI',user:'KANAME TŌSEN',title:'SENSORY ANALYTICS',command:'BANKAI: SUZUMUSHI TSUISHIKI',purpose:'Remove noise until the signal is impossible to miss.',ability:'A black field suppresses everything except the insight.',accent:0x6578ff,mode:'void',projects:['Pattern recognition','Data mining','Model explainability'] },
  { name:'KINSHARA BUTŌDAN',user:'RŌJŪRŌ “ROSE” ŌTORIBASHI',title:'CREATIVE DIRECTION',command:'BANKAI: KINSHARA BUTŌDAN',purpose:'Design systems, interaction, motion and interfaces that communicate.',ability:'Music becomes illusion; design becomes an experience.',accent:0xffcf6b,mode:'gold',projects:['Design systems','Motion libraries','Interactive visual work'] },
  { name:'TEKKEN TACHIKAZE',user:'KENSEI MUGURUMA',title:'RAW PERFORMANCE',command:'BANKAI: TEKKEN TACHIKAZE',purpose:'Benchmarking, profiling and ruthless removal of bottlenecks.',ability:'Continuous contact means continuous concussive force.',accent:0xff5a3d,mode:'force',projects:['Algorithm optimization','Benchmark suites','Runtime tuning'] },
  { name:'SŌŌ ZABIMARU',user:'RENJI ABARAI',title:'GROWTH TRAJECTORY',command:'BANKAI: SŌŌ ZABIMARU',purpose:'Skills accumulate through projects, experiments and mentorship.',ability:'A skeletal serpent grows with every completed milestone.',accent:0xb979ff,mode:'snake',projects:['Career progression','Mentorship','Learning outcomes'] },
  { name:'RYŪMON HŌZŌKUMARU',user:'IKKAKU MADARAME',title:'COMPOUNDING EFFORT',command:'BANKAI: RYŪMON HŌZŌKUMARU',purpose:'Long projects reward patience and accumulated effort.',ability:'A crest fills until one decisive strike is possible.',accent:0xe74343,mode:'dragon',projects:['Long-term initiatives','Compounding learning','Year-scale goals'] },
  { name:'KŌŌ MONSHŌ',user:'CHŌJIRŌ SASAKIBE',title:'LEADERSHIP',command:'BANKAI: KŌŌ MONSHŌ',purpose:'Architecture is coordination: people, responsibilities and decisions.',ability:'Lightning creates a visible hierarchy of roles and dependencies.',accent:0xffe45c,mode:'lightning',projects:['Team projects','Delegation','Strategic planning'] },
  { name:'HAKKA NO TOGAME',user:'RUKIA KUCHIKI',title:'SACRIFICE & PERFECTION',command:'BANKAI: HAKKA NO TOGAME',purpose:'Some breakthroughs require removing what no longer belongs.',ability:'Absolute cold freezes the environment and forces a deliberate reset.',accent:0xdffaff,mode:'white',projects:['Difficult technical decisions','Course corrections','Focused simplification'] },
  { name:'KANNONBIRAKI BENIHIME ARATAME',user:'KISUKE URAHARA',title:'RESTRUCTURE & FIX',command:'BANKAI: KANNONBIRAKI BENIHIME ARATAME',purpose:'Debugging means opening the system and rebuilding the right part.',ability:'Anything in range can be split, restructured and stitched together.',accent:0xff7652,mode:'repair',projects:['Debugging','Architectural refactoring','System redesign'] },
  { name:'SAKAHADĒ',user:'SHINJI HIRAKO',title:'PERSPECTIVE SHIFT',command:'INVERSION // CAN’T FEAR YOUR OWN WORLD',purpose:'Invert assumptions. Reframe the problem.',ability:'Perspective itself becomes the weapon.',accent:0xffc45c,mode:'invert',projects:['Unconventional approaches','Blue-sky thinking','Paradigm shifts'] },
  { name:'SHINKA HAKKŌ KEN',user:'NANAO ISE / SHUNSUI KYŌRAKU',title:'SECURITY & PROTECTION',command:'DIVINE EIGHT MIRROR SWORD',purpose:'Good systems defend users, data and invariants.',ability:'A mirror absorbs hostile force and reflects it back.',accent:0xbdeeff,mode:'mirror',projects:['Cybersecurity','Encryption','Defensive architecture'] },
  { name:'UNNAMED BANKAI',user:'KENPACHI ZARAKI',title:'RAW IMPACT',command:'BANKAI // UNTAMED',purpose:'Ambitious work that changes the game.',ability:'Pure destructive output with no concern for elegance.',accent:0xff1738,mode:'berserk',projects:['Breakthrough builds','Highest-impact work','Game-changing experiments'] },
  { name:'RESURRECCIÓN // FINAL PORTAL',user:'MUSAB WAQAR',title:'CONTACT & NEXT ARC',command:'FINAL FORM: OPEN THE GATE',purpose:'A portfolio is a doorway. The next system can be built together.',ability:'The Bankai archive collapses into a single portal.',accent:0xffd166,mode:'final',projects:['Research collaboration','FYP / engineering collaboration','International MS / research opportunities'] },
];

const profile={name:'Musab Waqar',role:'Co-Founder & CTO @ NanoCoders',university:'BS Computer Science · FAST NUCES Peshawar',graduation:'June 2027',motto:'Foundation → Mechanism → Implementation → Optimization → Real-world usage'};
const tech=['C','C++','Python','TypeScript','React','Next.js','Docker','Apache Kafka','Spark','PySpark','Hadoop','NLP','RAG','Neo4j','Apache AGE','PostgreSQL','Databricks','Linux'];

export default function Home(){
  const mount=useRef<HTMLDivElement>(null); const activeRef=useRef(0); const lastWheel=useRef(0);
  const [active,setActive]=useState(0); const [menu,setMenu]=useState(false); const [muted,setMuted]=useState(false); const [selected,setSelected]=useState<string|null>(null);
  const goTo=(index:number)=>{const next=Math.max(0,Math.min(scenes.length-1,index)); if(next===activeRef.current)return; activeRef.current=next; setActive(next);};
  const current=scenes[active]; const progress=((active+1)/scenes.length)*100; const numbers=useMemo(()=>scenes.map((_,i)=>String(i+1).padStart(2,'0')),[]);

  useEffect(()=>{
    if(!mount.current)return; const root=mount.current;
    const scene=new THREE.Scene(); const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,160); camera.position.set(0,.2,10);
    const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; root.appendChild(renderer.domElement);
    const world=new THREE.Group(); scene.add(world);
    scene.add(new THREE.AmbientLight(0xffffff,.38)); const light=new THREE.DirectionalLight(0xffffff,2.2); light.position.set(3,6,8); scene.add(light);
    const mat=(color:number,opacity=.8,wire=false)=>new THREE.MeshToonMaterial({color,transparent:true,opacity,wireframe:wire,side:THREE.DoubleSide});
    const glow=(color:number,opacity=.5)=>new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false});
    const outline=(mesh:THREE.Mesh,color=0x050505)=>{const e=new THREE.EdgesGeometry(mesh.geometry);const l=new THREE.LineSegments(e,new THREE.LineBasicMaterial({color,transparent:true,opacity:.8}));mesh.add(l);};
    const ring=(r:number,c:number,t=.025)=>new THREE.Mesh(new THREE.TorusGeometry(r,t,8,96),glow(c,.5));
    const groups=scenes.map(()=>new THREE.Group()); groups.forEach(g=>{g.visible=false;world.add(g);});

    // Deep 3D anime stage: layered planes, grid floor, distant city-like blocks and star/ash field.
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(55,55,32,32),new THREE.MeshBasicMaterial({color:0x030405,transparent:true,opacity:.72,wireframe:true})); floor.rotation.x=-Math.PI/2; floor.position.y=-3.2; world.add(floor);
    for(let z=0;z<8;z++){const horizon=new THREE.Mesh(new THREE.PlaneGeometry(26,4),glow(0x26333c,.12));horizon.position.set(0,-1.4,-8-z*4);world.add(horizon);}
    for(let i=0;i<42;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.3+Math.random()*.9,.5+Math.random()*2.8,.5+Math.random()*1.5),mat(0x10151a,.32,true));b.position.set((Math.random()-.5)*22,-2.8, -6-Math.random()*28);world.add(b);}
    const starGeo=new THREE.BufferGeometry(); const starPos=new Float32Array(1400*3); for(let i=0;i<1400;i++){starPos[i*3]=(Math.random()-.5)*34;starPos[i*3+1]=(Math.random()-.5)*18;starPos[i*3+2]=-Math.random()*55;} starGeo.setAttribute('position',new THREE.BufferAttribute(starPos,3)); const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xeaf6ff,size:.025,transparent:true,opacity:.72,depthWrite:false})); scene.add(stars);

    const particles=(g:THREE.Group,count:number,c:number,spread=6)=>{const geo=new THREE.BufferGeometry();const p=new Float32Array(count*3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=Math.sqrt(Math.random())*spread;p[i*3]=Math.cos(a)*r;p[i*3+1]=(Math.random()-.5)*spread;p[i*3+2]=Math.sin(a)*r;}geo.setAttribute('position',new THREE.BufferAttribute(p,3));g.add(new THREE.Points(geo,new THREE.PointsMaterial({color:c,size:.035,transparent:true,opacity:.7,depthWrite:false,blending:THREE.AdditiveBlending})));};
    const blade=(g:THREE.Group,c:number,len=4,white=false)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(.12,len,.055),mat(white?0xffffff:c,.95));b.position.z=.15;outline(b);g.add(b);g.add(ring(.9,white?0xffffff:c,.02));};

    scenes.forEach((s,i)=>{const g=groups[i],c=s.accent;g.userData={baseY:0};g.add(ring(2.2+(i%3)*.35,c,.035));g.add(ring(3.5,c,.018));particles(g,i===4?700:360,c,5.2);
      if(['tensa','hybrid','spear','force'].includes(s.mode)){blade(g,c,s.mode==='spear'?7:4,s.mode==='hybrid');if(s.mode==='hybrid'){const b=new THREE.Mesh(new THREE.BoxGeometry(.22,4.8,.07),mat(0xffffff,.9));b.rotation.z=-.08;b.position.x=.45;outline(b);g.add(b);}}
      if(s.mode==='tensa'){const chain=new THREE.Group();for(let n=0;n<9;n++){const o=new THREE.Mesh(new THREE.TorusGeometry(.09,.025,6,16),glow(0xdde8ef,.8));o.position.set(.2+n*.07,-2+n*.18,.2);o.rotation.x=n*.5;chain.add(o);}g.add(chain);}
      if(s.mode==='petals'||s.mode==='gold'){for(let n=0;n<75;n++){const p=new THREE.Mesh(new THREE.PlaneGeometry(.06,.16),glow(s.mode==='petals'?(n%4?0xff75c8:0xffffff):c,.8));p.position.set((Math.random()-.5)*9,(Math.random()-.5)*7,(Math.random()-.5)*5);p.rotation.z=Math.random()*Math.PI;g.add(p);}}
      if(s.mode==='ice'||s.mode==='white'){for(let n=0;n<16;n++){const q=new THREE.Mesh(new THREE.ConeGeometry(.12+Math.random()*.18,1.1+Math.random()*1.5,5),mat(c,.55));q.position.set(Math.cos(n/16*Math.PI*2)*2.7,Math.sin(n/16*Math.PI*2)*2.2,(Math.random()-.5)*2);q.rotation.z=n/16*Math.PI*2;outline(q);g.add(q);}}
      if(['fire','dragon','berserk'].includes(s.mode)){const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,1),glow(c,.28));outline(core,0x1a0202);g.add(core);for(let n=0;n<34;n++){const e=new THREE.Mesh(new THREE.SphereGeometry(.025+Math.random()*.07,6,6),glow(0xffb04a,.9));e.position.set((Math.random()-.5)*7,(Math.random()-.5)*7,(Math.random()-.5)*4);g.add(e);}}
      if(s.mode==='giant'){const torso=new THREE.Mesh(new THREE.BoxGeometry(1.7,4.3,1),mat(c,.5,true));torso.position.y=.3;outline(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.78,16,12),mat(c,.6,true));head.position.y=2.9;outline(head);g.add(torso,head);for(const x of[-1,1]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.5,3.4,.55),mat(c,.45,true));arm.position.set(x*1.2,.5,0);arm.rotation.z=x*.15;g.add(arm);}}
      if(s.mode==='poison'||s.mode==='acid'){const orb=new THREE.Mesh(new THREE.SphereGeometry(1.7,28,20),glow(c,.2));g.add(orb);for(let n=0;n<9;n++)g.add(ring(.65+n*.18,c,.025));}
      if(s.mode==='lightning'){for(let n=0;n<15;n++){const q=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,4,5),glow(c,.9));const a=n/15*Math.PI*2;q.position.set(Math.cos(a)*3,Math.sin(a)*2,(Math.random()-.5)*2);q.rotation.z=Math.sin(a)*.7;g.add(q);}}
      if(s.mode==='repair'){for(let n=0;n<7;n++){const q=new THREE.Mesh(new THREE.BoxGeometry(.45,.45,.45),mat(n%2?c:0xffffff,.8));const a=n/7*Math.PI*2;q.position.set(Math.cos(a)*2.2,Math.sin(a)*2.2,0);outline(q);g.add(q);}}
      if(s.mode==='snake'){for(let n=0;n<18;n++){const q=new THREE.Mesh(new THREE.SphereGeometry(.12+n*.008,10,8),mat(n%2?c:0xffffff,.75));q.position.set(Math.cos(n*.48)*(.35+n*.11),Math.sin(n*.48)*(.35+n*.11),n*.06);g.add(q);}}
      if(s.mode==='void'){g.add(new THREE.Mesh(new THREE.SphereGeometry(3.1,32,24),new THREE.MeshBasicMaterial({color:0x02020a,transparent:true,opacity:.86})));g.add(ring(3.3,c,.04));}
      if(s.mode==='story'){for(let n=0;n<8;n++){const q=ring(.65+n*.34,c,.025);q.rotation.x=n*.25;q.rotation.y=n*.4;g.add(q);}}
      if(s.mode==='invert'){const q=new THREE.Mesh(new THREE.BoxGeometry(2.8,2.8,2.8),mat(c,.18,true));outline(q);g.add(q);g.add(new THREE.Mesh(new THREE.SphereGeometry(1.25,24,16),glow(0x7650ff,.18)));}
      if(s.mode==='mirror'||s.mode==='final'){const q=new THREE.Mesh(new THREE.OctahedronGeometry(2,1),mat(c,.18,true));outline(q);g.add(q,ring(1.65,0xffffff,.04));}
    });

    const wheel=(e:WheelEvent)=>{const now=performance.now();if(now-lastWheel.current<520)return;if(Math.abs(e.deltaY)<14)return;lastWheel.current=now;goTo(activeRef.current+(e.deltaY>0?1:-1));};
    const keydown=(e:KeyboardEvent)=>{if(e.key==='ArrowDown'||e.key==='PageDown'||e.key===' '){e.preventDefault();goTo(activeRef.current+1)}if(e.key==='ArrowUp'||e.key==='PageUp'){e.preventDefault();goTo(activeRef.current-1)}if(e.key==='Escape'){setMenu(false);setSelected(null)}};
    addEventListener('wheel',wheel,{passive:true});addEventListener('keydown',keydown);

    // Deliberately no time-based object animation: the 3D world is frozen until scroll changes the scene.
    let raf=0; const render=()=>{const idx=activeRef.current;groups.forEach((g,i)=>g.visible=i===idx);renderer.render(scene,camera);raf=requestAnimationFrame(render)};render();
    const resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};addEventListener('resize',resize);
    return()=>{cancelAnimationFrame(raf);removeEventListener('wheel',wheel);removeEventListener('keydown',keydown);removeEventListener('resize',resize);renderer.dispose();root.removeChild(renderer.domElement)};
  },[]);

  useEffect(()=>{gsap.fromTo('.scene-copy',{opacity:0,y:34,filter:'blur(8px)'},{opacity:1,y:0,filter:'blur(0px)',duration:.55,ease:'power4.out'});gsap.fromTo('.scene-card',{opacity:0,x:25},{opacity:1,x:0,duration:.45,stagger:.045,ease:'power3.out'});},[active]);

  return <main className={`portfolio anime-${current.mode}`} style={{'--scene-accent':`#${current.accent.toString(16).padStart(6,'0')}`} as React.CSSProperties}>
    <div ref={mount} className="webgl"/><div className="anime-speedlines"/><div className="anime-ink"/><div className="vignette"/><div className="scanlines"/>
    <div key={`impact-${active}`} className="impact-frame"><span>卍</span></div>
    <header className="topbar"><button className="brand" onClick={()=>goTo(0)}>MW<span>.</span></button><div className="system-label">BANKAI ARCHIVE <b>//</b> MUSAB WAQAR</div><div className="top-actions"><button onClick={()=>setMuted(!muted)}>{muted?'SOUND OFF':'SOUND ON'}</button><button onClick={()=>setMenu(!menu)}>MENU <span>{menu?'×':'☰'}</span></button></div></header>
    <div className="hud-top"><span>REIATSU // {String(Math.round(progress)).padStart(3,'0')}</span><span>ONLINE · 22 BANKAIS</span></div>
    <div className="hud-left">{profile.name.toUpperCase()}<br/><span>{profile.role.toUpperCase()}</span></div>
    <div className="scene-index"><span>{String(active+1).padStart(2,'0')}</span><div className="index-line"><i style={{height:`${progress}%`}}/></div><span>22</span></div>
    <section className="scene-copy"><div className="eyebrow">{current.user} · BANKAI ARCHIVE</div><h1>{current.title}</h1><div className="bankai-name">{current.name}</div><p>{current.purpose}</p><div className="command"><span>RELEASE</span>{current.command}</div><div className="ability"><b>ABILITY</b>{current.ability}</div><div className="actions"><button className="primary" onClick={()=>setSelected(current.projects[0])}>OPEN ARCHIVE</button>{active<21&&<button className="ghost" onClick={()=>goTo(active+1)}>NEXT BANKAI →</button>}</div></section>
    <aside className="archive-panel"><div className="panel-kicker">{String(active+1).padStart(2,'0')} / 22 · PORTFOLIO TRANSLATION</div><h2>{current.title}</h2>{current.projects.map((p,i)=><button className="scene-card" key={p} onClick={()=>setSelected(p)}><span>0{i+1}</span><strong>{p}</strong><em>VIEW</em></button>)}<div className="tech-strip">{tech.slice((active*3)%tech.length,(active*3)%tech.length+5).map(t=><span key={t}>{t}</span>)}</div></aside>
    <div className="bottom-meta"><span>FOUNDATION → MECHANISM → IMPLEMENTATION → OPTIMIZATION</span><span>{profile.university} · {profile.graduation}</span></div>
    {active===0&&<div className="intro-mark">BANKAI<br/><small>THE PORTFOLIO AWAKENS</small></div>}
    {menu&&<div className="menu-overlay"><div className="menu-head"><span>GOTEI 13 // ARCHIVE</span><button onClick={()=>setMenu(false)}>CLOSE ×</button></div><div className="menu-grid">{scenes.map((s,i)=><button key={s.name} className={i===active?'selected':''} onClick={()=>{goTo(i);setMenu(false)}}><small>{String(i+1).padStart(2,'0')}</small><b>{s.name}</b><span>{s.title}</span></button>)}</div><div className="menu-footer">{profile.motto}</div></div>}
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="archive-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">ARCHIVE NODE · {current.name}</div><h2>{selected}</h2><p>Mapped to Musab Waqar’s engineering journey: practical systems, AI, distributed infrastructure, research and continuous experimentation.</p><div className="modal-tags">{current.projects.map(p=><span key={p}>{p}</span>)}</div><div className="modal-links"><a href="https://github.com/AbyssDev247/musabwaqar-3d-portfolio" target="_blank" rel="noreferrer">GITHUB →</a><a href="https://musabwaqar-3d-portfolio.vercel.app" target="_blank" rel="noreferrer">LIVE PORTFOLIO →</a><a href="https://github.com/Musab-Waqar" target="_blank" rel="noreferrer">GITHUB PROFILE →</a></div></article></div>}
    <div className="contact-dock"><a href="https://github.com/Musab-Waqar" target="_blank" rel="noreferrer">GITHUB</a><a href="https://musab-waqar-portfolio.vercel.app" target="_blank" rel="noreferrer">PORTFOLIO</a><a href="mailto:musab@fast.edu">EMAIL</a></div>
  </main>;
}
